trigger:
  branches:
    include:
    - master

jobs:
- job: Deploy
  steps:
  - task: UseDotNet@2
    displayName: Use .NET Core 6.0
    inputs:
      sdk: '6.0'

  - task: DotNetCoreCLI@2
    displayName: Build
    command: build

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
      artifactName: drop
      targetPath: $(Build.ArtifactStagingDirectory)

- job: Deploy to App Service
  steps:
  - task: AzureAppServiceDeploy@2
    displayName: Deploy to Azure App Service
    inputs:
      azureSubscription: $(azureSubscription)
      appName: greciapymesproyecto.azurewebsites.net
      slotName: $(azureSlotName)
      artifactName: drop
